In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available.Using CPU")

GPU is available
Using GPU: Tesla T4


## Creating a tensor

In [3]:
# using empty
a=torch.empty(2,3)
a

tensor([[1.4013e-45, 0.0000e+00, 2.2010e-13],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
b=torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
c=torch.ones(2,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
d=torch.rand(2,3) # random values betn  0 to 1
d

tensor([[0.6939, 0.7902, 0.4916],
        [0.5319, 0.5582, 0.7708]])

In [8]:
torch.rand(2,3) # random values

tensor([[0.5209, 0.4787, 0.8593],
        [0.0452, 0.0697, 0.5171]])

In [9]:
# use of seed (for reproducability)
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
x=[[1,2,3],[4,5,6]]
torch.tensor(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

#arange
print("using arange -> ",torch.arange(start=0,end=10,step=2))

#using linspace
print("using linspace -> ",torch.linspace(start=0,end=10,steps=10))

#using eye
print("using eye -> ",torch.eye(n=5)) # identity matrix of 5*5

#using full
print("using full -> ",torch.full(size=(3,3),fill_value=5))

using arange ->  tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [13]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

#### to have same shape of x

In [15]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 7148446506372523363]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
# torch.rand_like(x)

In [19]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data types

In [20]:
# find the data type
x=torch.tensor([[1,2,3],[4,5,6]])
print(x)
x.dtype

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.int64

In [21]:
# assign data type using dtype
a=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64)
print(a)
b=torch.tensor([1.0,2.0,3.0],dtype=torch.int32)
b

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


tensor([1, 2, 3], dtype=torch.int32)

In [22]:
# using to()
x=torch.tensor([[1,2,3],[4,5,6]])
x.to(dtype=torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operations

## 1.Scalar Operation(Element wise operation with single tensor)

In [23]:
x=torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

####  remember x will be getting changes in every step

In [24]:
# addition
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [25]:
# subtraction
x -2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [26]:
# multiplication
x * 3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [27]:
# division
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [28]:
# int division
(x*100)//3   # remember x is getting changes in every step

tensor([[23., 26.],
        [13., 30.]])

In [29]:
# mod
x % 2

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [30]:
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

## 2.ELement wise operation(betn 2 tensors)


In [31]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [32]:
# add
a+b


tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [33]:
# sub
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [34]:
#multiply
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [35]:
#division
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [36]:
# power
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [37]:
# mod
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

## some other for single tensor

In [38]:
c=torch.tensor([1,-2,3,-4])

In [39]:
# abs
c=torch.tensor([1,-2,3,-4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [40]:
# neg
torch.neg(c)

tensor([-1,  2, -3,  4])

In [41]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [42]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [43]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [44]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [45]:
# clamp
torch.clamp(d,min=2,max=3) # values should be betn 2 and 3,less than 2 will be 2,greater than 3 will be 3

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3.Reduction Operation (reduce everything to one value)


In [46]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [47]:
# sum
torch.sum(e) # adding everything

tensor(24.)

In [48]:
# sum along columns
torch.sum(e,dim=0)

tensor([ 8.,  0., 16.])

In [49]:
# sum along rows
torch.sum(e,dim=1)

tensor([15.,  9.])

In [50]:
# mean
torch.mean(e) # mean of everything

tensor(4.)

In [51]:
# mean along column
torch.mean(e,dim=0)

tensor([4., 0., 8.])

In [52]:
#mean along rows
torch.mean(e,dim=1)

tensor([5., 3.])

In [53]:
# median
torch.median(e)

tensor(0.)

In [54]:
# max and min
torch.max(e)

tensor(9.)

In [55]:
torch.min(e)

tensor(0.)

In [56]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [57]:
# variance
torch.var(e)

tensor(19.6000)

In [58]:
#argmax
torch.argmax(e) #provides the index position of maximum value from tensor

tensor(5)

In [59]:
# argmin
torch.argmin(e) # provides the index position of minimum value from tensor

tensor(1)

## 4.Matrix Operations

In [60]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [61]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [62]:
# dot product
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

torch.dot(vector1,vector2)

tensor(11)

In [63]:
# transpose
f=torch.randint(size=(2,3),low=0,high=10)
print(f)
torch.transpose(f,dim0=0,dim1=1) # swap dim 0 column with dim 1 row (transpose)

tensor([[5, 9, 8],
        [9, 7, 9]])


tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [64]:
# determinant (only works for square matrix)

In [65]:
#square matrix
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [66]:
torch.det(h)

tensor(-315.)

In [67]:
# inverse (only works for square matrix)
torch.inverse(h)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

## 5.Comparsion operations(element wise checking)

In [68]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[3, 3, 5],
        [0, 6, 4]])


In [69]:
# greater than        (element wise checking)
i>j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [70]:
# less than
i<j

tensor([[False,  True,  True],
        [False, False, False]])

In [71]:
# equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [72]:
# not equal to
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [73]:
# greater than equal to
i>=j

tensor([[ True, False, False],
        [ True,  True,  True]])

## 6.Special functions(Element wise)

In [74]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[0., 8., 4.],
        [7., 2., 3.]])

In [75]:
# log
torch.log(k)

tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [76]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [77]:
#sqrt
torch.sqrt(k)

tensor([[0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321]])

In [78]:
#sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [79]:
# softmax
torch.softmax(k,dim=0)

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [80]:
# relu
torch.relu(k)

tensor([[0., 8., 4.],
        [7., 2., 3.]])

## Inplace Operations

In [81]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])
tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [82]:
m+n # will return new tensor of same size,and this may be bad if we r having storage issue,and the tensors are very large

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [83]:
m.add_(n)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [84]:
m # m is taking the sum value in its own position

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [85]:
n

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [86]:
torch.relu(m) # return new tensor


tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [87]:
m.relu_() # returned tensor gets on m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

## Copying a Tensor

In [88]:
a=torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [89]:
b=a

In [90]:
b

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [91]:
a[0][0]=0
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [92]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [93]:
id(a)

135843882177616

In [94]:
id(b) # same memory location because of reference

135843882177616

# use clone

In [95]:
b=a.clone()

In [96]:
a


tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [97]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [98]:
a[0][0]=10
a

tensor([[10.0000,  0.8935,  0.0497],
        [ 0.1780,  0.3011,  0.1893]])

In [99]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [100]:
id(a)

135843882177616

In [101]:

id(b)

135838485977904

## Tensor Operations on GPU

In [102]:
torch.cuda.is_available()

True

In [103]:
device=torch.device("cuda")

In [104]:
# creating a new tensor on GPU
torch.rand(size=(2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [107]:
# move an existing tensor on GPU
a=torch.rand(2,3) # this is made on cpu(by default if device not specified)
print(a)
b=a.to(device=device) # moved to gpu
print(b)


tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])
tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]], device='cuda:0')


In [108]:
b + 5 # operation performed on gpu

tensor([[5.6594, 5.0887, 5.4890],
        [5.5887, 5.7340, 5.8497]], device='cuda:0')

### Speed Comparison betn CPU and GPU

In [110]:
import torch
import time

# define the size of the matrices
size=10000 # large size for performance comparison


#create random matrices on CPU
matrix_cpu1=torch.randn(size=(size,size))
matrix_cpu2=torch.randn(size=(size,size))

#Measure time on CPU
start_time=time.time()
result_cpi=torch.matmul(matrix_cpu1,matrix_cpu2) # matrix multiplication on CPU
cpu_time=time.time()-start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

#Move matrices on GPU
matrix_gpu1=matrix_cpu1.to("cuda")
matrix_gpu2=matrix_cpu2.to("cuda")

#Measure time on GPU
start_time=time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time=time.time()-start_time

print(f"Time on GPU : {gpu_time:.4f} seconds")


#Compare results
print(f"\n Speedup (CPU time/GPU time) : {cpu_time/gpu_time}")

Time on CPU: 15.7355 seconds
Time on GPU : 0.8360 seconds

 Speedup (CPU time/GPU time) : 18.82216861986055


## Reshaping Tensors

In [111]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [112]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [113]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [115]:
# 3. permute() - reorders dimensions
# Create a 3D tensor (2, 3, 4)
b=torch.rand(2,3,4)
b

tensor([[[0.8186, 0.0463, 0.7306, 0.2009],
         [0.3265, 0.6684, 0.3509, 0.7772],
         [0.2353, 0.4301, 0.4385, 0.7375]],

        [[0.5494, 0.7109, 0.0148, 0.7262],
         [0.4660, 0.0610, 0.7108, 0.5127],
         [0.8211, 0.1323, 0.2127, 0.9785]]])

In [116]:
# Permute dimensions: move dimension 2 (index 2) to front, then 0, then 1
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [117]:
# unsqueeze
c=torch.rand(226,226,3) # typical image size
c.unsqueeze(dim=0).shape

torch.Size([1, 226, 226, 3])

In [118]:
c.unsqueeze(dim=1).shape

torch.Size([226, 1, 226, 3])

In [119]:
# squeeze
d=torch.rand(size=(1,20))
d.squeeze(0).shape

torch.Size([20])

## Numpy and torch

In [120]:
import torch
import numpy as np

##### converting tensor to numpy

In [121]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [122]:
b=a.numpy()
b

array([1, 2, 3])

In [123]:
type(b)

numpy.ndarray

##### converting numpy to tensor

In [125]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [126]:
torch.from_numpy(c)

tensor([1, 2, 3])