In [51]:
import torch
print(torch.__version__)

2.10.0+cu128


In [52]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available.Using CPU")

GPU is available
Using GPU: Tesla T4


## Creating a tensor

In [53]:
# using empty
a=torch.empty(2,3)
a

tensor([[1.2064e-40, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [54]:
# check type
type(a)

torch.Tensor

In [55]:
# using zeros
b=torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [56]:
# using ones
c=torch.ones(2,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [57]:
# using rand
d=torch.rand(2,3) # random values betn  0 to 1
d

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [58]:
torch.rand(2,3) # random values

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [59]:
# use of seed (for reproducability)
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [60]:
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [61]:
# using tensor
x=[[1,2,3],[4,5,6]]
torch.tensor(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [62]:
# other ways

#arange
print("using arange -> ",torch.arange(start=0,end=10,step=2))

#using linspace
print("using linspace -> ",torch.linspace(start=0,end=10,steps=10))

#using eye
print("using eye -> ",torch.eye(n=5)) # identity matrix of 5*5

#using full
print("using full -> ",torch.full(size=(3,3),fill_value=5))

using arange ->  tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [63]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [64]:
x.shape

torch.Size([2, 3])

#### to have same shape of x

In [65]:
torch.empty_like(x)

tensor([[8238222649317746032, 8028075780950158945,   28147497671059822],
        [                  0,            16777216,        107156144128]])

In [66]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [67]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [68]:
# torch.rand_like(x)

In [69]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data types

In [70]:
# find the data type
x=torch.tensor([[1,2,3],[4,5,6]])
print(x)
x.dtype

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.int64

In [71]:
# assign data type using dtype
a=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64)
print(a)
b=torch.tensor([1.0,2.0,3.0],dtype=torch.int32)
b

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


tensor([1, 2, 3], dtype=torch.int32)

In [72]:
# using to()
x=torch.tensor([[1,2,3],[4,5,6]])
x.to(dtype=torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operations

## 1.Scalar Operation(Element wise operation with single tensor)

In [74]:
x=torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

####  remember x will be getting changes in every step

In [75]:
# addition
x + 2

tensor([[2.9969, 2.7565],
        [2.2239, 2.3023]])

In [76]:
# subtraction
x -2

tensor([[-1.0031, -1.2435],
        [-1.7761, -1.6977]])

In [77]:
# multiplication
x * 3

tensor([[2.9907, 2.2695],
        [0.6717, 0.9070]])

In [78]:
# division
x/3

tensor([[0.3323, 0.2522],
        [0.0746, 0.1008]])

In [80]:
# int division
(x*100)//3   # remember x is getting changes in every step

tensor([[33., 25.],
        [ 7., 10.]])

In [81]:
# mod
x % 2

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [82]:
# power
x**2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

## 2.ELement wise operation(betn 2 tensors)


In [83]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])
tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])


In [84]:
# add
a+b


tensor([[0.9229, 1.3130, 0.7983],
        [1.6774, 0.9717, 1.1950]])

In [85]:
# sub
a-b

tensor([[-0.5661,  0.3346,  0.3132],
        [ 0.2767, -0.0837,  0.7007]])

In [86]:
#multiply
a*b

tensor([[0.1328, 0.4030, 0.1348],
        [0.6842, 0.2343, 0.2343]])

In [87]:
#division
a/b

tensor([[0.2397, 1.6841, 2.2912],
        [1.3951, 0.8415, 3.8346]])

In [88]:
# power
a**b

tensor([[0.2771, 0.9096, 0.8672],
        [0.9839, 0.6515, 0.9868]])

In [89]:
# mod
a%b

tensor([[0.1784, 0.3346, 0.0706],
        [0.2767, 0.4440, 0.2063]])

## some other for single tensor

In [92]:
c=torch.tensor([1,-2,3,-4])

In [90]:
# abs
c=torch.tensor([1,-2,3,-4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [91]:
# neg
torch.neg(c)

tensor([-1,  2, -3,  4])

In [94]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [95]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [96]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [97]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [99]:
# clamp
torch.clamp(d,min=2,max=3) # values should be betn 2 and 3,less than 2 will be 2,greater than 3 will be 3

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3.Reduction Operation (reduce everything to one value)


In [105]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[4., 0., 5.],
        [7., 5., 9.]])

In [106]:
# sum
torch.sum(e) # adding everything

tensor(30.)

In [107]:
# sum along columns
torch.sum(e,dim=0)

tensor([11.,  5., 14.])

In [108]:
# sum along rows
torch.sum(e,dim=1)

tensor([ 9., 21.])

In [109]:
# mean
torch.mean(e) # mean of everything

tensor(5.)

In [110]:
# mean along column
torch.mean(e,dim=0)

tensor([5.5000, 2.5000, 7.0000])

In [111]:
#mean along rows
torch.mean(e,dim=1)

tensor([3., 7.])

In [112]:
# median
torch.median(e)

tensor(5.)

In [114]:
# max and min
torch.max(e)

tensor(9.)

In [115]:
torch.min(e)

tensor(0.)

In [116]:
# standard deviation
torch.std(e)

tensor(3.0332)

In [117]:
# variance
torch.var(e)

tensor(9.2000)

In [118]:
#argmax
torch.argmax(e) #provides the index position of maximum value from tensor

tensor(5)

In [119]:
# argmin
torch.argmin(e) # provides the index position of minimum value from tensor

tensor(1)

## 4.Matrix Operations

In [121]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[8, 3, 6],
        [1, 5, 5]])
tensor([[0, 4],
        [3, 8],
        [8, 3]])


In [122]:
# matrix multiplication
torch.matmul(f,g)

tensor([[57, 74],
        [55, 59]])

In [123]:
# dot product
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

torch.dot(vector1,vector2)

tensor(11)

In [130]:
# transpose
f=torch.randint(size=(2,3),low=0,high=10)
print(f)
torch.transpose(f,dim0=0,dim1=1) # swap dim 0 column with dim 1 row (transpose)

tensor([[2, 3, 1],
        [0, 2, 1]])


tensor([[2, 0],
        [3, 2],
        [1, 1]])

In [131]:
# determinant (only works for square matrix)

In [132]:
#square matrix
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[2., 7., 9.],
        [2., 4., 6.],
        [6., 8., 4.]])

In [133]:
torch.det(h)

tensor(60.0000)

In [134]:
# inverse (only works for square matrix)
torch.inverse(h)

tensor([[-0.5333,  0.7333,  0.1000],
        [ 0.4667, -0.7667,  0.1000],
        [-0.1333,  0.4333, -0.1000]])

## 5.Comparsion operations(element wise checking)

In [135]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[9, 0, 7],
        [9, 2, 7]])
tensor([[0, 2, 4],
        [4, 6, 2]])


In [137]:
# greater than        (element wise checking)
i>j

tensor([[ True, False,  True],
        [ True, False,  True]])

In [138]:
# less than
i<j

tensor([[False,  True, False],
        [False,  True, False]])

In [139]:
# equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [140]:
# not equal to
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [141]:
# greater than equal to
i>=j

tensor([[ True, False,  True],
        [ True, False,  True]])

## 6.Special functions(Element wise)

In [149]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[2., 2., 3.],
        [7., 1., 5.]])

In [150]:
# log
torch.log(k)

tensor([[0.6931, 0.6931, 1.0986],
        [1.9459, 0.0000, 1.6094]])

In [151]:
# exp
torch.exp(k)

tensor([[   7.3891,    7.3891,   20.0855],
        [1096.6332,    2.7183,  148.4132]])

In [152]:
#sqrt
torch.sqrt(k)

tensor([[1.4142, 1.4142, 1.7321],
        [2.6458, 1.0000, 2.2361]])

In [153]:
#sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.8808, 0.9526],
        [0.9991, 0.7311, 0.9933]])

In [154]:
# softmax
torch.softmax(k,dim=0)

tensor([[0.0067, 0.7311, 0.1192],
        [0.9933, 0.2689, 0.8808]])

In [155]:
# relu
torch.relu(k)

tensor([[2., 2., 3.],
        [7., 1., 5.]])

## Inplace Operations

In [159]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.6555, 0.7667, 0.2269],
        [0.7555, 0.6458, 0.3673]])
tensor([[0.1770, 0.2966, 0.9925],
        [0.2103, 0.1292, 0.1719]])


In [160]:
m+n # will return new tensor of same size,and this may be bad if we r having storage issue,and the tensors are very large

tensor([[0.8325, 1.0633, 1.2194],
        [0.9659, 0.7750, 0.5392]])

In [161]:
m.add_(n)

tensor([[0.8325, 1.0633, 1.2194],
        [0.9659, 0.7750, 0.5392]])

In [162]:
m # m is taking the sum value in its own position

tensor([[0.8325, 1.0633, 1.2194],
        [0.9659, 0.7750, 0.5392]])

In [163]:
n

tensor([[0.1770, 0.2966, 0.9925],
        [0.2103, 0.1292, 0.1719]])

In [164]:
torch.relu(m) # return new tensor


tensor([[0.8325, 1.0633, 1.2194],
        [0.9659, 0.7750, 0.5392]])

In [165]:
m.relu_() # returned tensor gets on m

tensor([[0.8325, 1.0633, 1.2194],
        [0.9659, 0.7750, 0.5392]])

## Copying a Tensor

In [181]:
a=torch.rand(2,3)
a

tensor([[0.1450, 0.7819, 0.3134],
        [0.2983, 0.3436, 0.2028]])

In [182]:
b=a

In [183]:
b

tensor([[0.1450, 0.7819, 0.3134],
        [0.2983, 0.3436, 0.2028]])

In [184]:
a[0][0]=0
a

tensor([[0.0000, 0.7819, 0.3134],
        [0.2983, 0.3436, 0.2028]])

In [185]:
b

tensor([[0.0000, 0.7819, 0.3134],
        [0.2983, 0.3436, 0.2028]])

In [186]:
id(a)

135325906614176

In [187]:
id(b) # same memory location because of reference

135325906614176

# use clone

In [188]:
b=a.clone()

In [189]:
a


tensor([[0.0000, 0.7819, 0.3134],
        [0.2983, 0.3436, 0.2028]])

In [190]:
b

tensor([[0.0000, 0.7819, 0.3134],
        [0.2983, 0.3436, 0.2028]])

In [191]:
a[0][0]=10
a

tensor([[10.0000,  0.7819,  0.3134],
        [ 0.2983,  0.3436,  0.2028]])

In [192]:
b

tensor([[0.0000, 0.7819, 0.3134],
        [0.2983, 0.3436, 0.2028]])

In [193]:
id(a)

135325906614176

In [194]:

id(b)

135325906306384