## Topic 3: Practical - Setting up Environment & Checking GPU

In [13]:
## python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

## for windows gpu 

In [14]:
import torch
# Check PyTorch version
print("PyTorch Version:", torch.__version__)
# Check if GPU is available
print("Is CUDA (GPU) available?", torch.cuda.is_available())
# If GPU is available, get its name
if torch.cuda.is_available():
 print("GPU Name:", torch.cuda.get_device_name(0))
else:
 print("GPU not available. Using CPU.")

PyTorch Version: 2.11.0
Is CUDA (GPU) available? False
GPU not available. Using CPU.


### only for mac

MPS (Metal Performance Shaders) in PyTorch enables GPU acceleration for machine learning on macOS (12.3+), specifically using Apple Silicon (M1/M2/M3/M4) or AMD GPUs. By setting the device to "mps", tensors and models are moved to the GPU, significantly speeding up training and inference compared to the CPU.

In [12]:
import torch
print(f"PyTorch version: {torch.__version__}")
print(f"MPS available: {torch.backends.mps.is_available()}")
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("✅ Using MPS (Apple Silicon GPU)")
else:
    device = torch.device("cpu") 
    print("❌ Using CPU")

PyTorch version: 2.11.0
MPS available: True
✅ Using MPS (Apple Silicon GPU)


## Topic 4: Creating Tensors
- Here are the most important methods to create tensors.

In [15]:
import torch
# 1. torch.empty(): Allocates memory without initializing (values are whatever was in memory).
a = torch.empty(2, 3) # Creates a 2x3 tensor
print("torch.empty:\n", a)
# 2. torch.zeros(): Creates a tensor filled with zeros.
b = torch.zeros(2, 3)
print("\ntorch.zeros:\n", b)
# 3. torch.ones(): Creates a tensor filled with ones.
c = torch.ones(2, 3)
print("\ntorch.ones:\n", c)
# 4. torch.rand(): Creates a tensor with random values between 0 and 1.
d = torch.rand(2, 3)
print("\ntorch.rand:\n", d)
# 5. For reproducibility with random numbers, set a seed.
torch.manual_seed(100)
e = torch.rand(2, 3)
print("\ntorch.rand with seed 100:\n", e)
# 6. torch.tensor(): Creates a tensor from a Python list or NumPy array.
f = torch.tensor([[4, 5, 6], [7, 8, 9]])
print("\ntorch.tensor from list:\n", f)
# 7. Other useful methods
g = torch.arange(0, 10, 2) # torch.arange(start, end, step)
print("\ntorch.arange:\n", g)
h = torch.linspace(0, 10, 5) # torch.linspace(start, end, steps)
print("\ntorch.linspace:\n", h)
i = torch.eye(3) # Identity matrix
print("\ntorch.eye:\n", i)
j = torch.full((2, 3), 5) # Tensor of shape 2x3 filled with value 5
print("\ntorch.full:\n", j)

torch.empty:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

torch.zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

torch.ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

torch.rand:
 tensor([[0.3092, 0.1497, 0.1993],
        [0.9438, 0.9449, 0.9905]])

torch.rand with seed 100:
 tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

torch.tensor from list:
 tensor([[4, 5, 6],
        [7, 8, 9]])

torch.arange:
 tensor([0, 2, 4, 6, 8])

torch.linspace:
 tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

torch.eye:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

torch.full:
 tensor([[5, 5, 5],
        [5, 5, 5]])


## Topic 5: Tensor Shape and Data Type

In [17]:
x = torch.tensor([[4, 5, 6], [7, 8, 9]])
# 1. Getting shape
print("Shape of x:", x.shape) # or x.size()
print("Number of dimensions (rank):", x.dim())
print("Total number of elements:", x.numel())
# 2. Getting data type
print("Data type of x:", x.dtype)
# 3. Specifying data type during creation
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
float_tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
print("\nInteger Tensor:", int_tensor)
print("Float Tensor:", float_tensor)
# 4. Changing data type of an existing tensor
x_float = x.to(torch.float32)
print("\nOriginal x dtype:", x.dtype)
print("New x_float dtype:", x_float.dtype)
# 5. Using the `like` functions
y = torch.rand_like(x_float) # Creates a random tensor of same shape as x_float
print("\nrand_like (float):\n", y)

Shape of x: torch.Size([2, 3])
Number of dimensions (rank): 2
Total number of elements: 6
Data type of x: torch.int64

Integer Tensor: tensor([1, 2, 3], dtype=torch.int32)
Float Tensor: tensor([1., 2., 3.])

Original x dtype: torch.int64
New x_float dtype: torch.float32

rand_like (float):
 tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Topic 6: Mathematical Operations

## 6.1 Scalar Operations
- (Element wise operation with single tensor)
- Operations between a tensor and a single number.

In [6]:
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
print("Original x:", x)
print("x + 2:", x + 2)
print("x - 2:", x - 2)
print("x * 2:", x * 2)
print("x / 2:", x / 2)
print("x ** 2 (power):", x ** 2)

Original x: tensor([1., 2., 3., 4.])
x + 2: tensor([3., 4., 5., 6.])
x - 2: tensor([-1.,  0.,  1.,  2.])
x * 2: tensor([2., 4., 6., 8.])
x / 2: tensor([0.5000, 1.0000, 1.5000, 2.0000])
x ** 2 (power): tensor([ 1.,  4.,  9., 16.])


## 6.2 Element-wise Operations
- Operations between two tensors of the same shape.


In [7]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print("a + b:", a + b)
print("a * b:", a * b)
print("a / b:", a / b)
print("a //b :",a//b)

a + b: tensor([5, 7, 9])
a * b: tensor([ 4, 10, 18])
a / b: tensor([0.2500, 0.4000, 0.5000])
a //b : tensor([0, 0, 0])


### 6.3 Other Element-wise Functions

In [ ]:
t = torch.tensor([-1.9, 2.3, -3.7, 4.4])
print("Absolute:", torch.abs(t))
print("Negative:", torch.negative(t))
print("Round:", torch.round(t))
print("Ceil (upper integer):", torch.ceil(t))
print("Floor (lower integer):", torch.floor(t))
# Clamp: limits values to a range
print("Clamp between 2 and 3:", torch.clamp(t, min=2, max=3))
# values should be betn 2 and 3,less than 2 will be 2,greater than 3 will be 3

Absolute: tensor([1.9000, 2.3000, 3.7000, 4.4000])
Negative: tensor([ 1.9000, -2.3000,  3.7000, -4.4000])
Round: tensor([-2.,  2., -4.,  4.])
Ceil (upper integer): tensor([-1.,  3., -3.,  5.])
Floor (lower integer): tensor([-2.,  2., -4.,  4.])
Clamp between 2 and 3: tensor([2.0000, 2.3000, 2.0000, 3.0000])


### 3.Reduction Operation (reduce everything to one value)


In [18]:
e = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print("Tensor e:\n", e)
print("Sum of all elements:", torch.sum(e))
print("Mean of all elements:", torch.mean(e))
# Sum over dimension 0 (rows -> column-wise sum)
print("Sum over dimension 0:", torch.sum(e, dim=0)) # Result shape (3)
# Sum over dimension 1 (columns -> row-wise sum)
print("Sum over dimension 1:", torch.sum(e, dim=1)) # Result shape (2)
print("Maximum value:", torch.max(e))
print("Position of maximum value (argmax):", torch.argmax(e)) #Flattens tensor

Tensor e:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
Sum of all elements: tensor(21.)
Mean of all elements: tensor(3.5000)
Sum over dimension 0: tensor([5., 7., 9.])
Sum over dimension 1: tensor([ 6., 15.])
Maximum value: tensor(6.)
Position of maximum value (argmax): tensor(5)


In [24]:
# median
torch.median(e)

tensor(3.)

In [19]:
# standard deviation
torch.std(e)

tensor(1.8708)

In [21]:
# variance
torch.var(e)

tensor(3.5000)

In [59]:
# argmin
torch.argmin(e) # provides the index position of minimum value from tensor

tensor(1)

## 6.5 Matrix Operations

In [60]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [26]:
# Matrix Multiplication (mm)
f = torch.tensor([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
g = torch.tensor([[7, 8], [9, 10], [11, 12]]) # Shape (3, 2)
print("Matrix Multiplication (2x3 * 3x2 = 2x2):\n", torch.matmul(f, g))
# Dot Product (vectors)
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])
print("\nDot Product (1*3 + 2*4):", torch.dot(vector1, vector2))
# Transpose
print("\nOriginal f:\n", f)
print("Transpose of f:\n", torch.transpose(f,dim0=0,dim1=1)) # swap dim 0 column with dim 1 row (transpose)
     

Matrix Multiplication (2x3 * 3x2 = 2x2):
 tensor([[ 58,  64],
        [139, 154]])

Dot Product (1*3 + 2*4): tensor(11)

Original f:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Transpose of f:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [27]:
# determinant (only works for square matrix)
#square matrix
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(h)
#determinant
torch.det(h)

tensor([[8., 8., 4.],
        [4., 1., 0.],
        [4., 3., 8.]])


tensor(-160.)

In [28]:
# inverse (only works for square matrix)
torch.inverse(h)

tensor([[-0.0500,  0.3250,  0.0250],
        [ 0.2000, -0.3000, -0.1000],
        [-0.0500, -0.0500,  0.1500]])

## 5.Comparsion operations(element wise checking)

In [68]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[3, 3, 5],
        [0, 6, 4]])


In [69]:
# greater than        (element wise checking)
i>j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [70]:
# less than
i<j

tensor([[False,  True,  True],
        [False, False, False]])

In [71]:
# equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [72]:
# not equal to
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [73]:
# greater than equal to
i>=j

tensor([[ True, False, False],
        [ True,  True,  True]])

## 6.Special functions(Element wise)

In [74]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[0., 8., 4.],
        [7., 2., 3.]])

In [75]:
# log
torch.log(k)

tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [76]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [77]:
#sqrt
torch.sqrt(k)

tensor([[0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321]])

In [78]:
#sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [79]:
# softmax
torch.softmax(k,dim=0)

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [80]:
# relu
torch.relu(k)

tensor([[0., 8., 4.],
        [7., 2., 3.]])

## Topic 7: In-Place Operations (The _ Suffix)
- In-place operations modify the original tensor directly, saving memory

In [ ]:
m = torch.tensor([1, 2, 3])
n = torch.tensor([4, 5, 6])
# Non-in-place: creates a new tensor
result = m + n# will return new tensor of same size,and this may be bad if we r having storage issue,and the tensors are very large
print("m after non-in-place addition:", m) # m is unchanged
# In-place: modifies m directly
m.add_(n) # Equivalent to m = m + n, but modifies m in-place # m is taking the sum value in its own position
print("m after in-place addition (add_):", m)

m after non-in-place addition: tensor([1, 2, 3])
m after in-place addition (add_): tensor([5, 7, 9])


In [33]:
# In-place ReLU activation
a = torch.tensor([-1, 2, -3, 4])
a.relu_() # Replaces negative values with 0
print("\na after in-place ReLU (relu_):", a)


a after in-place ReLU (relu_): tensor([0, 2, 0, 4])


## Topic 8: Copying Tensors (Clone vs. Assignment)
- Assignment (=): Creates a new reference to the same memory location. Changes to one
affect the other.
-  clone(): Creates a new, independent copy in a new memory location

In [35]:
a = torch.tensor([1, 2, 3])
print("Original a:", a)
# Shallow copy using assignment
b = a
print("b = a, b:", b)
# Modify a
a[0] = 100
print("\na after change:", a)
print("b after a changed:", b) # b changes because it points to the same memory
# Deep copy using clone
c = a.clone()
a[1] = 200
print("\na after further change:", a)
print("c after a changed (clone):", c) # c remains unchanged
print("\nMemory IDs:")
print("ID of a:", id(a))
print("ID of b (assigned):", id(b)) # Same as a
print("ID of c (cloned):", id(c)) # Different from a

Original a: tensor([1, 2, 3])
b = a, b: tensor([1, 2, 3])

a after change: tensor([100,   2,   3])
b after a changed: tensor([100,   2,   3])

a after further change: tensor([100, 200,   3])
c after a changed (clone): tensor([100,   2,   3])

Memory IDs:
ID of a: 4687265632
ID of b (assigned): 4687265632
ID of c (cloned): 4664902256


## Topic 9: Moving Tensors to GPU

## checking on windows 

In [ ]:
# 1. Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
# 2. Create a tensor directly on the GPU(need to specify device)
gpu_tensor = torch.rand(2, 3, device=device)
print("\nTensor created on GPU:\n", gpu_tensor)
print("Device of gpu_tensor:", gpu_tensor.device)
# 3. Move an existing CPU tensor to GPU
cpu_tensor = torch.rand(2, 3)# this is made on cpu(by default if device not specified)
print("\nCPU tensor device:", cpu_tensor.device)
gpu_tensor_2 = cpu_tensor.to(device)
print("GPU tensor device after .to():", gpu_tensor_2.device)
# 4. Speed comparison (example code)
if torch.cuda.is_available():
 import time
 size = 10000
 cpu_a = torch.rand(size, size)
 cpu_b = torch.rand(size, size)
 # CPU Computation
 start = time.time()
 cpu_result = torch.matmul(cpu_a, cpu_b)
 cpu_time = time.time() - start
 # GPU Computation
 gpu_a = cpu_a.to(device)
 gpu_b = cpu_b.to(device)
 start = time.time()
 gpu_result = torch.matmul(gpu_a, gpu_b) # Wait for GPU to finish
 torch.cuda.synchronize() # Ensure all GPU operations are complete
 gpu_time = time.time() - start
 print(f"\nCPU time for {size}x{size} matmul: {cpu_time:.2f}seconds")
 print(f"GPU time for {size}x{size} matmul: {gpu_time:.2f} seconds")
 print(f"Speedup: {cpu_time/gpu_time:.2f}x")

## checking on mac

In [ ]:
# 1. Check if GPU is available
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print("Using device:", device)

# 2. Create a tensor directly on the GPU
gpu_tensor = torch.rand(2, 3, device=device)
print("\nTensor created on GPU:\n", gpu_tensor)
print("Device of gpu_tensor:", gpu_tensor.device)

# 3. Move an existing CPU tensor to GPU
cpu_tensor = torch.rand(2, 3)
print("\nCPU tensor device:", cpu_tensor.device)
gpu_tensor_2 = cpu_tensor.to(device)
print("GPU tensor device after .to():", gpu_tensor_2.device)

# 4. Speed comparison (example code)
if torch.backends.mps.is_available():
    import time
    size = 10000
    cpu_a = torch.rand(size, size)
    cpu_b = torch.rand(size, size)
    
    # CPU Computation
    start = time.time()
    cpu_result = torch.matmul(cpu_a, cpu_b)
    cpu_time = time.time() - start
    
    # GPU Computation
    gpu_a = cpu_a.to(device)
    gpu_b = cpu_b.to(device)
    start = time.time()
    gpu_result = torch.matmul(gpu_a, gpu_b)
    torch.mps.synchronize()  # Wait for MPS to finish,# Ensure all GPU operations are complete
    gpu_time = time.time() - start
    
    print(f"\nCPU time for {size}x{size} matmul: {cpu_time:.2f} seconds")
    print(f"GPU time for {size}x{size} matmul: {gpu_time:.2f} seconds")
    print(f"Speedup: {cpu_time/gpu_time:.2f}x")

Using device: mps

Tensor created on GPU:
 tensor([[0.7897, 0.4016, 0.2065],
        [0.6310, 0.3886, 0.6892]], device='mps:0')
Device of gpu_tensor: mps:0

CPU tensor device: cpu
GPU tensor device after .to(): mps:0

CPU time for 10000x10000 matmul: 2.60 seconds
GPU time for 10000x10000 matmul: 1.69 seconds
Speedup: 1.54x


In [102]:
torch.cuda.is_available()

True

In [103]:
device=torch.device("cuda")

In [104]:
# creating a new tensor on GPU
torch.rand(size=(2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [107]:
# move an existing tensor on GPU
a=torch.rand(2,3) # this is made on cpu(by default if device not specified)
print(a)
b=a.to(device=device) # moved to gpu
print(b)


tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])
tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]], device='cuda:0')


In [108]:
b + 5 # operation performed on gpu

tensor([[5.6594, 5.0887, 5.4890],
        [5.5887, 5.7340, 5.8497]], device='cuda:0')

### Speed Comparison betn CPU and GPU

In [110]:
import torch
import time

# define the size of the matrices
size=10000 # large size for performance comparison


#create random matrices on CPU
matrix_cpu1=torch.randn(size=(size,size))
matrix_cpu2=torch.randn(size=(size,size))

#Measure time on CPU
start_time=time.time()
result_cpi=torch.matmul(matrix_cpu1,matrix_cpu2) # matrix multiplication on CPU
cpu_time=time.time()-start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

#Move matrices on GPU
matrix_gpu1=matrix_cpu1.to("cuda")
matrix_gpu2=matrix_cpu2.to("cuda")

#Measure time on GPU
start_time=time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time=time.time()-start_time

print(f"Time on GPU : {gpu_time:.4f} seconds")


#Compare results
print(f"\n Speedup (CPU time/GPU time) : {cpu_time/gpu_time}")

Time on CPU: 15.7355 seconds
Time on GPU : 0.8360 seconds

 Speedup (CPU time/GPU time) : 18.82216861986055


## Topic 10: Reshaping Tensors

In [41]:
# Create a tensor of shape (4, 4)
r = torch.arange(16).reshape(4, 4)
print("Original tensor (4x4):\n", r)
# 1. reshape()
reshaped = r.reshape(2, 8)
print("\nReshape to (2, 8):\n", reshaped)
# 2. flatten()
flat = r.flatten()
print("\nFlattened (1D):", flat)
# 3. permute() - reorders dimensions
# Create a 3D tensor (2, 3, 4)
p = torch.arange(24).reshape(2, 3, 4)
print("\nOriginal 3D shape (2,3,4):", p.shape)
# Permute dimensions: move dimension 2 (index 2) to front, then 0,then 1
permuted = p.permute(2, 0, 1)
print("Permuted shape (4,2,3):", permuted.shape)
# 4. unsqueeze() - adds a dimension of size 1
img = torch.rand(226, 226, 3) # Example image shape
print("\nImage shape:", img.shape)
batch_img = img.unsqueeze(0) # Add batch dimension at position 0
print("After unsqueeze (batch added):", batch_img.shape) # (1, 226,226, 3)
# 5. squeeze() - removes dimensions of size 1
batch_removed = batch_img.squeeze(0)
print("After squeeze (batch removed):", batch_removed.shape)

Original tensor (4x4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

Reshape to (2, 8):
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])

Flattened (1D): tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Original 3D shape (2,3,4): torch.Size([2, 3, 4])
Permuted shape (4,2,3): torch.Size([4, 2, 3])

Image shape: torch.Size([226, 226, 3])
After unsqueeze (batch added): torch.Size([1, 226, 226, 3])
After squeeze (batch removed): torch.Size([226, 226, 3])


## Topic 11: Interoperability with NumPy and torch

In [43]:
import numpy as np
# 1. PyTorch Tensor -> NumPy Array
tensor = torch.tensor([1, 2, 3])
print("PyTorch Tensor:", tensor)
numpy_array = tensor.numpy()
print("Converted NumPy Array:", numpy_array)
print("Type:", type(numpy_array))


# 2. NumPy Array -> PyTorch Tensor
np_array = np.array([4, 5, 6])
print("\nNumPy Array:", np_array)
tensor_from_np = torch.from_numpy(np_array)
print("Converted PyTorch Tensor:", tensor_from_np)
print("Type:", type(tensor_from_np))

PyTorch Tensor: tensor([1, 2, 3])
Converted NumPy Array: [1 2 3]
Type: <class 'numpy.ndarray'>

NumPy Array: [4 5 6]
Converted PyTorch Tensor: tensor([4, 5, 6])
Type: <class 'torch.Tensor'>
